from pathlib import Path
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Preformatted
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'output/pdf/AES-GCM-Project-Guide-Hinglish.pdf'
OUT.parent.mkdir(parents=True, exist_ok=True)
styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='BodyGuide', fontName='Helvetica', fontSize=10.3, leading=14.5, textColor=colors.HexColor('#25364a'), spaceAfter=8))
styles.add(ParagraphStyle(name='TitleGuide', fontName='Helvetica-Bold', fontSize=26, leading=31, textColor=colors.HexColor('#102b46'), spaceAfter=15))
styles.add(ParagraphStyle(name='SubGuide', fontName='Helvetica-Bold', fontSize=14, leading=19, textColor=colors.HexColor('#087f80'), spaceBefore=12, spaceAfter=8))
styles.add(ParagraphStyle(name='SmallGuide', fontName='Helvetica', fontSize=8.5, leading=11.5, textColor=colors.HexColor('#25364a'), spaceAfter=3))
styles.add(ParagraphStyle(name='CodeGuide', fontName='Courier', fontSize=8.2, leading=12, backColor=colors.HexColor('#eef3f7'), borderPadding=10, spaceBefore=5, spaceAfter=12))
styles.add(ParagraphStyle(name='BoxGuide', fontName='Helvetica-Bold', fontSize=11, leading=16, alignment=TA_CENTER, textColor=colors.HexColor('#102b46')))
story=[]
def p(text): story.append(Paragraph(text, styles['BodyGuide']))
def title(num,text,sub):
    story.append(Paragraph(f'PROJECT GUIDE / {num:02}',styles['SmallGuide']))
    story.append(Spacer(1,7)); story.append(Paragraph(text,styles['TitleGuide'])); p(sub)
def h(text): story.append(Paragraph(text,styles['SubGuide']))
def code(text): story.append(Preformatted(text,styles['CodeGuide']))
def table(headers,rows,widths):
    data=[[Paragraph(x,styles['SmallGuide']) for x in headers]]+[[Paragraph(x,styles['SmallGuide']) for x in row] for row in rows]
    t=Table(data,colWidths=widths,hAlign='LEFT')
    t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#dcecf0')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),9),('RIGHTPADDING',(0,0),(-1,-1),9),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7),('LINEBELOW',(0,0),(-1,0),.7,colors.HexColor('#087f80')),('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white,colors.HexColor('#f4f7fa')])]))
    story.append(t); story.append(Spacer(1,10))
def nextpage(): story.append(PageBreak())

title(1,'AES-GCM project\nSimple Hinglish guide','Angular + .NET Gateway + .NET API | Learning, maintenance aur future changes')
p('<b>Project owner:</b> Faiz Noor &nbsp; | &nbsp; <b>Date:</b> 04 October 2026<br/><b>Code baseline:</b> d3a2b38 &nbsp; | &nbsp; <b>Branch:</b> codex/initial-setup')
h('Humne kya banaya?')
p('Login/register wali Angular app banayi hai. Request ka JSON Angular mein encrypt hota hai. Gateway encrypted envelope aage bhejta hai. API data decrypt karke kaam karti hai aur response encrypt karti hai. Angular response decrypt karke screen par dikhata hai.')
flow=Table([[Paragraph('ANGULAR<br/>4200<br/>Encrypt / decrypt',styles['BoxGuide']),Paragraph('&gt;',styles['BoxGuide']),Paragraph('GATEWAY<br/>5100<br/>Forward envelope',styles['BoxGuide']),Paragraph('&gt;',styles['BoxGuide']),Paragraph('.NET API<br/>5200<br/>Decrypt / process',styles['BoxGuide'])]],colWidths=[145,25,145,25,145])
flow.setStyle(TableStyle([('BACKGROUND',(0,0),(0,0),colors.HexColor('#e5f5ef')),('BACKGROUND',(2,0),(2,0),colors.HexColor('#e8eef7')),('BACKGROUND',(4,0),(4,0),colors.HexColor('#e5f5ef')),('TOPPADDING',(0,0),(-1,-1),18),('BOTTOMPADDING',(0,0),(-1,-1),18),('VALIGN',(0,0),(-1,-1),'MIDDLE')]))
story.append(flow)
h('Teen modules complete hain')
table(['Module','Kya ready hai'],[['1. Foundation','Angular app, gateway/API projects, health check aur local routing.'],['2. Encryption','Session setup, AES-256-GCM request/response, encrypted echo, tamper/replay checks.'],['3. Authentication','Register, login, password hashing, protected profile aur token-revoking logout.']],[125,360])
h('Is guide ko kaise padho')
p('Pages 2-3 se flow samjho. Page 4 ko file map ki tarah use karo. Page 5 future feature add karne ka recipe hai. Pages 6-7 run commands, tests aur common errors ke liye hain.')
p('<b>Scope:</b> Ye single-process learning demo hai. Users memory mein hain. API restart se accounts reset hote hain; browser refresh se login clear hota hai. Deployment mein authenticated HTTPS chahiye.')
nextpage()

title(2,'Encryption kaise chalti hai?','Pehle session banti hai, phir har message encrypt/decrypt hota hai.')
h('Step 1: keys establish karna')
p('<b>1.</b> Angular temporary P-256 public/private key pair banata hai. Public key <b>POST /api/crypto/session</b> ko bhejta hai. Private key browser mein rehti hai.')
p('<b>2.</b> API apna temporary pair banati hai. Dono public keys se ECDH shared secret derive hota hai. API public key, random salt, session ID aur expiry return karti hai.')
p('<b>3.</b> Dono sides HKDF-SHA256 se do alag AES-256 keys derive karti hain: request ke liye ek, response ke liye ek. AES keys network par send nahi hoti. Crypto session 10 minutes valid hai.')
h('Step 2: encrypted round trip')
p('<b>4.</b> Angular JSON ko bytes mein badalta hai, fresh 12-byte nonce banata hai, phir AES-GCM encrypt karta hai. Result ciphertext aur 16-byte tag hai.')
p('<b>5.</b> Gateway envelope forward karta hai. API tag verify karke decrypt karti hai. Verification fail hui toh business handler run nahi hota.')
p('<b>6.</b> API business result ko response key aur fresh nonce se encrypt karti hai. Angular matching request ID check karta hai, tag verify karta hai, phir response decrypt karta hai.')
table(['Term','Simple matlab'],[['Ciphertext','Original JSON ka encrypted form.'],['Nonce / IV','Har encryption ka fresh random 12-byte value. Same key ke saath reuse mat karo.'],['Tag','Authentication check: data ya bound metadata badli toh decrypt fail hota hai.'],['AAD','Visible metadata jo tag se protect hoti hai: session ID, request ID, POST, route aur direction.'],['Base64','Bytes ko JSON mein carry karne ka encoding format. Ye encryption nahi hai.']],[110,375])
h('Wire par kya dikhega?')
code('{ "sessionId": "...", "requestId": "...",\n  "nonce": "Base64...", "ciphertext": "Base64...",\n  "tag": "Base64..." }')
p('Session/request IDs aur route visible hain. JSON body encrypted hai. Session bootstrap aur health plaintext hain; isliye HTTPS bhi zaroori hai. Web Crypto tag ciphertext ke end mein deta hai; client usko split karta hai, kyunki .NET AesGcm separate tag leta hai.')
nextpage()

title(3,'Register se logout tak','Crypto session data protect karti hai. Login token user ki identity verify karta hai.')
h('Register')
p('Form name/email/password leta hai. AuthService encrypted transport call karta hai. API decrypt karke validation karti hai; email lowercase normalize hota hai. PasswordHasher salted password hash banata hai. Plain password store nahi hota. Registration ke baad user ko login karna hota hai.')
h('Login')
p('API password hash verify karti hai. Success par random 256-bit opaque token banta hai. Ye JWT nahi hai. Token encrypted response mein aata hai; Angular service memory mein rakhti hai. API token ka SHA-256 lookup hash store karti hai. Login 30 minutes valid hai.')
h('Profile aur logout')
p('Profile request ke encrypted JSON mein token jaata hai. API independently token validate karke sirf id/name/email return karti hai. Logout token record remove karta hai; us token se future profile request reject hoti hai. Route guard sirf navigation help hai; actual protection API mein hai.')
table(['POST route','Decrypted request','Application result'],[['/api/auth/register','name, email, password','ok, message, user'],['/api/auth/login','email, password','ok, message, user, token'],['/api/auth/me','token','ok, message, user'],['/api/auth/logout','token','ok, message']],[160,150,175])
p('<b>Public routes:</b> GET /api/health; POST /api/crypto/session. <b>Demo route:</b> POST /api/secure/echo encrypted payload receive karke echo karta hai.')
h('Response samajhne ka rule')
p('Valid encrypted request ka business result HTTP 200 ke andar encrypted aata hai. Wrong password bhi decrypted <b>ok: false</b> deta hai. Sirf HTTP 200 dekhkar login successful mat samjho. Invalid encrypted envelope jaise protocol errors plaintext HTTP 400/409 ho sakte hain.')
h('Abhi data kahan hai?')
p('API: users, salted hashes, token hashes aur crypto sessions memory mein. Angular: login token aur AES keys memory mein. localStorage, sessionStorage aur cookies use nahi hote. Auth credentials/tokens lab ke debug panels mein nahi dikhte.')
nextpage()

title(4,'Code ka map','Saare paths repository root se relative hain. Change se pehle related files saath padho.')
table(['File / location','Responsibility aur useful entry point'],[['src/client/src/app/encrypted-transport.ts','connect/createSession: ECDH + HKDF.<br/>encrypt/decrypt: AES-GCM, tag split/join.<br/>post: complete encrypted HTTP round trip.'],['src/Demo.Api/Transport/SessionStore.cs','Create: session keys/expiry.<br/>Process: decrypt, replay check, handler run, encrypt result.<br/>Echo: Process ka demo wrapper.'],['src/Demo.Api/Auth/AuthStore.cs','Handle: auth operation dispatch.<br/>Register/LoginUser: validation/hash verification.<br/>Token lookup, expiry, lockout, logout.'],['src/Demo.Api/Program.cs','Services register karta hai; health, crypto, echo aur auth routes map karta hai.'],['src/Demo.Gateway/Program.cs','Allowed routes check; request/response forward; timeout aur unavailable backend handle karta hai.'],['src/client/src/app/auth.service.ts','register/login/profile/logout calls; memory-only token aur user signal.'],['src/client/src/app/auth-page.ts + auth-page.html + auth-page.css','Login/register form, confirmation, submission status aur styling.'],['src/client/src/app/profile.ts','Protected profile verify karna aur logout.'],['src/client/src/app/app.routes.ts','login/register/profile/lab routes; profile navigation guard.'],['src/client/src/app/app.ts + app.html + app.css','App shell aur navigation.'],['src/client/src/app/lab.ts + lab.html + lab.css','Encrypted echo screen aur synthetic wire-payload debug panels.'],['src/client/proxy.conf.json','Development mein /api/** ko gateway:5100 par bhejta hai.'],['scripts/verify-transport.mjs + verify-auth.mjs','Real Web Crypto/.NET integration, tamper/replay aur authentication checks.']],[232,253])
p('<b>Reading order:</b> AuthPage.submit() -> AuthService.login() -> EncryptedTransport.post() -> gateway -> API route -> SessionStore.Process() -> AuthStore.Handle() -> encrypted response.')
nextpage()

title(5,'Future change kahan karna hai?','Example: baad mein encrypted Update Profile feature add karna ho.')
h('Naya encrypted endpoint add karne ka recipe')
p('<b>1. Contract:</b> Route decide karo, jaise POST /api/profile/update. Decrypted request mein token aur new name ho; response mein ok/message/user ho. Pehle exact field names decide karo.')
p('<b>2. Backend logic:</b> Profile service mein token validate karo, name validate karo, phir data update karo. Encryption session ko login proof mat samjho.')
p('<b>3. API route:</b> Demo.Api/Program.cs mein route map karo. SessionStore.Process(envelope, exactRoute, handler) se decrypted JSON handler tak aur result encrypted response tak pahunchao.')
p('<b>4. Gateway:</b> Demo.Gateway/Program.cs ki allowed-route list mein same POST path add karo. Ye step miss hua toh gateway 404 dega.')
p('<b>5. Angular:</b> AuthService mein transport.post(exactRoute, payload) use karo. Form/component aur zarurat ho toh app.routes.ts mein page add karo. Token ko auth service ke andar rakho.')
p('<b>6. Verification:</b> Build aur integration checks run karo. Valid update, invalid token, validation failure, tampering aur replay cover karo. Phir module ka Git commit/push karo.')
h('Common changes ka shortcut')
table(['Change','Files / attention'],[['Colors, form layout, labels','auth-page.html/css; app.html/css; lab.html/css.'],['New register field','Form + AuthService payload + Credentials/validation + public response + tests.'],['API port change','API Properties/launchSettings.json + gateway ApiBaseUrl setting.'],['Gateway port change','Gateway launchSettings.json + client proxy.conf.json.'],['Crypto session expiry','SessionStore.Create: AddMinutes(10). Client renewal/expiry behavior recheck karo.'],['Login expiry / password policy','AuthStore: AddMinutes(30), validation; Angular form/help text aur tests update karo.'],['Database add karna','AuthStore users dictionary ko persistent repository se replace karo. Password hashes hi save karo; token expiry/revocation preserve karo.']],[160,325])
p('<b>Crypto rule:</b> AAD ka method/path/direction, HKDF labels, key length ya envelope format change karo toh Angular aur .NET dono update karo. Known interoperability/tamper tests dobara run karo.')
nextpage()

title(6,'Project run aur test karna','Windows PowerShell mein repository root se start karo. Teen alag terminals chahiye.')
h('Setup aur startup')
p('Installed project baseline: Angular 21; Node 20.19+ compatible baseline; .NET 8 target. .NET SDK ke saath .NET 8 runtime bhi available hona chahiye. Client dependencies ek baar install karo:')
code('cd src/client\nnpm ci\ncd ../..')
p('<b>Terminal 1 - API:</b>')
code('dotnet run --project src/Demo.Api')
p('<b>Terminal 2 - gateway:</b>')
code('dotnet run --project src/Demo.Gateway')
p('<b>Terminal 3 - Angular:</b>')
code('cd src/client\nnpm start')
p('Browser: <b>http://localhost:4200/register</b> -> account banao -> /login -> /profile -> logout. /lab par sample message encrypt karke wire aur decrypted result dekho.')
h('Build aur automated checks')
code('# Repository root\ndotnet build AesGcmDemo.sln\n# Client directory\ncd src/client\nnpm run build\ncd ../..\n# API + gateway running hone chahiye\nnode scripts/verify-transport.mjs\nnode scripts/verify-auth.mjs')
p('Angular dev proxy bhi exercise karna ho toh Angular running rakho aur root se:')
code("$env:DEMO_URL = 'http://localhost:4200'\nnode scripts/verify-auth.mjs\nRemove-Item Env:DEMO_URL")
p('<b>Verified baseline:</b> .NET/Angular builds aur transport/auth integration checks pass hue. Scripts Node Web Crypto se actual client transport run karte hain. Browser clicks ki automated verification host browser-control runtime failure ki wajah se pending thi.')
nextpage()

title(7,'Errors, limits aur reference','Problem aaye toh pehle ye checks dekho; phir related file map use karo.')
table(['Symptom','Likely reason / action'],[['Connection failed / HTTP 502','API:5200 aur gateway:5100 running hain? ApiBaseUrl sahi hai?'],['HTTP 504','Backend gateway ke 10-second timeout ke andar respond nahi kar raha. API logs dekho.'],['HTTP 404 on new route','Gateway allowlist aur API route exact match karo.'],['HTTP 400 / decrypt failed','Nonce/tag size, ciphertext, AES key, AAD route/direction aur HKDF labels match karo. Envelope edit hua ho toh reject expected hai.'],['HTTP 409','Unknown/expired crypto session, replayed request ID ya request capacity. API restart hua ho toh browser refresh karke login dobara karo.'],['Login refresh ke baad gaya','Expected: browser token memory-only hai. Dobara login karo.'],['Registered account missing','API restart ne in-memory users clear kiye. Dobara register karo.'],['ok:false / too many attempts','Register/login ka global 60 attempts/minute budget. Minute wait karo. Five wrong passwords se account one minute locked hota hai.'],['Build file locked','Running API/gateway apne terminals mein Ctrl+C se stop karo; build, phir restart karo.']],[170,315])
h('Current demo limits')
p('Crypto session: 10 min; login: 30 min; 1,000 active crypto sessions; 1,000 accepted requests/session; 1,000 users aur login records each. Bootstrap global 30 requests/minute. Request bodies 32 KiB max; client plaintext 16,000 bytes max. Sensitive responses no-store hain.')
h('Deployment se pehle')
p('Authenticated HTTPS, supported patched runtimes, persistent identity storage aur multiple API instances ke liye shared-state design chahiye. Browser mein malicious JavaScript chale toh AES usse protect nahi karega. Current operations simple locks se serialize hoti hain; ye high-traffic architecture nahi hai.')
h('Project aur references')
p('<b>Repository:</b><br/><link href="https://github.com/noorfaiz115/angular-dotnet-aes-gcm-demo" color="#087f80">github.com/noorfaiz115/angular-dotnet-aes-gcm-demo</link>')
p('<b>Project docs:</b> README.md; docs/architecture.md; docs/module-2.md; docs/module-3.md. Ye guide current source code ko explain karti hai; suggested Update Profile feature abhi implement nahi hai.')
p('<b>API reference:</b> <link href="https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.aesgcm" color="#087f80">Microsoft AesGcm</link> | <link href="https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.passwordhasher-1" color="#087f80">Microsoft PasswordHasher</link> | <link href="https://www.w3.org/TR/WebCryptoAPI/" color="#087f80">W3C Web Crypto</link>')

def footer(canvas,doc):
    canvas.saveState(); w,h=A4
    canvas.setStrokeColor(colors.HexColor('#cdd8e2')); canvas.line(42,40,w-42,40)
    canvas.setFont('Helvetica',8); canvas.setFillColor(colors.HexColor('#607284'))
    canvas.drawString(42,27,'AES-GCM project | Simple Hinglish | Baseline d3a2b38')
    canvas.drawRightString(w-42,27,str(doc.page)); canvas.restoreState()
doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=55,leftMargin=55,topMargin=42,bottomMargin=56,title='AES-GCM Project Guide - Simple Hinglish',author='Faiz Noor / Codex')
doc.build(story,onFirstPage=footer,onLaterPages=footer)
reader=PdfReader(OUT)
print(f'Created {OUT}; pages={len(reader.pages)}')
for i,page in enumerate(reader.pages,1): print(f'Page {i}: {len(page.extract_text())} characters')

