import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from '../src/client/node_modules/typescript/lib/typescript.js';
const source = fs.readFileSync(new URL('../src/client/src/app/encrypted-transport.ts', import.meta.url), 'utf8');
const code = ts.transpileModule(source, { compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022 } }).outputText;
const { EncryptedTransport } = await import('data:text/javascript;base64,' + Buffer.from(code).toString('base64'));
const base = process.env.DEMO_URL ?? 'http://localhost:5100';
const transport = new EncryptedTransport(base);
const auth = async (operation, payload) => {
  const result = await transport.post('/api/auth/' + operation, payload);
  assert.equal('password' in result.plaintext, false);
  assert.equal('passwordHash' in result.plaintext, false);
  return result;
};
const email = `test-${crypto.randomUUID()}@example.com`;
const password = 'Only-Test-Password-42!';
assert.equal((await auth('register', { name: 'Test', email, password: 'short' })).plaintext.ok, false);
assert.equal((await auth('register', { name: 'Test', email: 'invalid', password })).plaintext.ok, false);
assert.equal((await auth('register', { name: ' ', email, password })).plaintext.ok, false);
assert.equal((await auth('register', [] )).plaintext.ok, false);
const registered = await auth('register', { name: 'नूर Test', email: email.toUpperCase(), password });
assert.equal(registered.plaintext.ok, true);
assert.equal(registered.plaintext.user.email, email);
assert.equal((await auth('register', { name: 'Duplicate', email, password })).plaintext.ok, false);
assert.equal((await auth('login', { email, password: 'Wrong-Password-42!' })).plaintext.ok, false);
assert.equal((await auth('login', { email: 'unknown@example.com', password })).plaintext.ok, false);
const login = await auth('login', { email, password });
assert.equal(login.plaintext.ok, true);
const token = login.plaintext.token;
assert.equal(token.length, 64);
const profile = (await auth('me', { token })).plaintext;
assert.equal(profile.ok, true);
assert.equal(profile.user.name, 'नूर Test');
assert.deepEqual(Object.keys(profile.user).sort(), ['email', 'id', 'name']);
assert.equal((await auth('me', {})).plaintext.ok, false);
assert.equal((await auth('me', { token: '0'.repeat(64) })).plaintext.ok, false);
// Transport session is not an identity: another session without a login token has no access.
const other = new EncryptedTransport(base);
assert.equal((await other.post('/api/auth/me', {})).plaintext.ok, false);
// Passwords never appear in the serialized wire request.
assert.equal(JSON.stringify(login.request).includes(password), false);
const damaged = await transport.encrypt('/api/auth/register', { name: 'Tampered', email: `bad-${crypto.randomUUID()}@example.com`, password });
const tag = Buffer.from(damaged.tag, 'base64'); tag[0] ^= 1;
const rejected = await fetch(base + '/api/auth/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...damaged, tag: tag.toString('base64') }) });
assert.equal(rejected.status, 400);
assert.equal((await auth('logout', { token })).plaintext.ok, true);
assert.equal((await auth('me', { token })).plaintext.ok, false, 'logout revokes token');
assert.equal((await auth('logout', { token })).plaintext.ok, false);
const lockedEmail = `lock-${crypto.randomUUID()}@example.com`;
await auth('register', { name: 'Lock Test', email: lockedEmail, password });
for (let i = 0; i < 5; i++) assert.equal((await auth('login', { email: lockedEmail, password: 'Wrong-Password-42!' })).plaintext.ok, false);
assert.equal((await auth('login', { email: lockedEmail, password })).plaintext.ok, false, 'temporary account lock');
const duplicateEmail = `race-${crypto.randomUUID()}@example.com`;
const registrations = await Promise.all([auth('register', { name: 'Race', email: duplicateEmail, password }), auth('register', { name: 'Race', email: duplicateEmail, password })]);
assert.equal(registrations.filter(x => x.plaintext.ok).length, 1, 'duplicate registration atomic');
console.log('PASS: encrypted registration/login/profile/logout, input validation, duplicate email, wrong credentials, missing/forged tokens, credential confidentiality, tampering, token revocation, account lock and registration race.');
